services:
  # Needed for development to allow modifications to the static folder but also being able to connect the local volume with the container
  backend-permissions-fix:
    image: alpine
    # The command to run. UID 65532 is the standard 'nonroot' user in distroless images
    command: sh -c 'chown -R 65532:65532 /data/static'
    volumes:
      - ./static:/data/static

  # Local firecrawl. It can be replaced by entering the correct APIKEY and using their services
  # Used for scrapping websites --> only used in URL ingestion
  firecrawl:
    image: ghcr.io/mendableai/firecrawl:latest
    ports:
      - "7331:3002"
    networks:
      - app-network
    environment:
      - HOST=0.0.0.0
      - REDIS_URL=redis://redis:6379
      - REDIS_RATE_LIMIT_URL=redis://redis:6379
    depends_on:
      - redis

  # Service needed for firecrawl to work
  redis:
    image: redis:alpine
    networks:
      - app-network
  
  backend:
    build:
      context: ./backend
      args:
        - REQUIREMENTS_FILE=requirements-cpu.txt
    ports:
      - "9090:9090"
    env_file:
      - backend/.env
    environment:
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - FIRECRAWL_API_URL=http://firecrawl:3002
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
      - kb-data:/home/nonroot/data
    networks:
      - app-network
    depends_on:
      - firecrawl
      - redis
  
  # Frontend to debug the backend service
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    environment:
      - LAMB_WEBAPP_PORT=9091
      - LAMB_KB_SERVER_URL=http://backend:9090
    volumes:
      - ./webapp:/app
    networks:
      - app-network
    depends_on:
      - backend

  # Run unit tests
  backend-tests:
    build:
      context: ./backend
      target: builder
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env 

networks:
  app-network:
    driver: bridge

volumes:
  kb-data:
    name: lamb-kb-data
  static-files:
    name: lamb-static-files