version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9090:9090"
    env_file:
      - backend/.env
    environment:
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - FIRECRAWL_API_URL=${FIRECRAWL_API_URL}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    volumes:
      - ./backend:/app/backend
      - ./static:/app/static
      - kb-data:/app/data
    networks:
      - app-network
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:9090
      - API_TOKEN=0p3n-w3bu!
    depends_on:
      - backend
    networks:
      - app-network

  ollama:
    build:
      context: ./ollama
      args:
        OLLAMA_EMBEDDING_MODEL: ${EMBEDDINGS_MODEL}
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  kb-data:
    name: lamb-kb-data
  static-files:
    name: lamb-static-files
  ollama-data:
    name: lamb-ollama-data